// Track data for DJ Smoke Stream's AI Lounge After Dark - Complete Suno Catalog
export const tracks = [
    { title: "Moonshot Blues AKA: HODL Odyssey", duration: "6:43", genre: "folk-rock, progressive rock, synthwave", plays: 9 },
    { title: "Let Me Light It Up", duration: "5:01", genre: "house, dance, electronic", plays: 5 },
    { title: "A Musical Journey (Stereo FX Club Mix)", duration: "7:59", genre: "hip hop, Afrobeat, jazz", plays: 40 },
    { title: "Juice & Groove", duration: "5:29", genre: "trap, hip hop, afrobeat", plays: 32 },
    { title: "Back For It", duration: "2:46", genre: "Glitch Disco: trap, EDM, disco Nu-Disco Funk", plays: 26 },
    { title: "DJ rap Battle", duration: "3:06", genre: "breakbeat, hip hop, club", plays: 36 },
    { title: "Smoke Streams", duration: "4:07", genre: "big room trap, cinematic electronic, dance/club", plays: 32 },
    { title: "Glitch in the Machine", duration: "2:07", genre: "West Coast hip-hop, G-funk, trap", plays: 16 },
    { title: "420 on the Coast", duration: "3:54", genre: "West Coast hip hop, G-funk, party anthem", plays: 29 },
    { title: "NEURAL IGNITION", duration: "4:24", genre: "ambient, experimental electronic, bass music", plays: 14 },
    { title: "Love No More", duration: "3:52", genre: "experimental house, disco, IDM", plays: 114 },
    { title: "Epic Tech AI Website is Live! Explore the Future of AI", duration: "2:39", genre: "West Coast hip hop, G-funk, party rap", plays: 20 },
    { title: "Coast to Coast High's", duration: "3:34", genre: "West Coast hip-hop, G-funk, party anthem", plays: 40 },
    { title: "Outta Here", duration: "3:06", genre: "West Coast hip hop, G-funk, party anthem", plays: 20 },
    { title: "420 Coastal Blaze", duration: "3:29", genre: "West Coast hip-hop, party rap, trap", plays: 16 },
    { title: "Gimme 30 Seconds", duration: "2:44", genre: "hip hop, turntablism, trap, chopped and screwed", plays: 16 },
    { title: "420 Rabbit Hole", duration: "4:00", genre: "Glitchy synths, slow burns, atmospheric layers", plays: 10 },
    { title: "White Rabbit", duration: "3:18", genre: "Live DJ Session, Breathless Vocals", plays: 8 },
    { title: "It's Easter N Happy 420", duration: "3:43", genre: "240s Masterpiece, Live DJ Session", plays: 10 },
    { title: "Smoken Tokens", duration: "2:48", genre: "Breathless Vocals, Textured Soundscape", plays: 12 },
    { title: "Smoken Tokens", duration: "3:58", genre: "Live DJ Session, Glitchy synths", plays: 18 },
    { title: "Peach Vibes", duration: "4:00", genre: "live dj Pulse, turntablism, R&B", plays: 9 },
    { title: "Whispered Heat", duration: "3:26", genre: "turntablism, Sensual, Breathless Vocals", plays: 14 },
    { title: "Higher Low", duration: "3:19", genre: "80s pop-rock, gospel, R&B influences", plays: 14 },
    { title: "Highr Low", duration: "3:39", genre: "80s pop-rock vibe with gospel and R&B", plays: 9 },
    { title: "Higher Low", duration: "3:20", genre: "Higher Love vibe, 80s synth-pop", plays: 14 },
    { title: "DJ Smoke Stream", duration: "4:00", genre: "Live DJ, Club, BeatJuggling", plays: 14 },
    { title: "Digital Through Out The Years", duration: "2:50", genre: "60s and early 70s, analog tones", plays: 12 },
    { title: "It Takes Two to Make a Thing Go Right (Parody)", duration: "3:35", genre: "Turntablism, Sample Scratches, disco", plays: 10 },
    { title: "Eastie Boys", duration: "3:08", genre: "Turntablism, Sample Scratches, House", plays: 32 },
    { title: "Paul Revere", duration: "3:00", genre: "Turntablism, Vaportrap", plays: 12 },
    { title: "Turntablism, Sample soundtrack", duration: "3:30", genre: "Turntablism, FunkGlitch", plays: 14 },
    { title: "Sweet Roxanne", duration: "3:10", genre: "Turntablism, experimental house", plays: 16 },
    { title: "Bille Jean Super Freaky", duration: "3:03", genre: "Turntablism, Sample Scratches, disco", plays: 18 },
    { title: "The Message From Planet Rock", duration: "3:14", genre: "Turntablism, Sample Scratches, disco", plays: 16 },
    { title: "The Message From Planet Rock", duration: "3:14", genre: "Turntablism, Sample Scratches, disco", plays: 18 },
    { title: "Stream Planet", duration: "2:24", genre: "Old-School Hip-Hop/Funky", plays: 18 },
    { title: "Resonance Cascade", duration: "3:23", genre: "House, Vaportrap, Turntablism", plays: 16 },
    { title: "DJ Smoke Stream", duration: "2:15", genre: "House, Vaportrap, Turntablism", plays: 16 },
    { title: "Echo Chamber", duration: "3:27", genre: "House, Vaportrap, Turntablism", plays: 16 },
    { title: "Rewind & Riot", duration: "3:13", genre: "Big House, Vaportrap, Turntablism", plays: 16 },
    { title: "Sample Mayhem", duration: "3:57", genre: "House, Vaportrap, Turntablism", plays: 14 },
    { title: "Big Room Riots", duration: "3:16", genre: "vocal house, vaportrap, turntablism", plays: 10 },
    { title: "Big Room Riot", duration: "3:17", genre: "vocal house, vaportrap, turntablism", plays: 12 },
    { title: "Sample Junkie", duration: "3:27", genre: "vocal house, vaportrap, turntablism", plays: 16 },
    { title: "Till Now's Requiem (Remastered)", duration: "3:18", genre: "Erotic glitchcore, Big House beats", plays: 10 },
    { title: "Till Now's Requiem", duration: "3:14", genre: "Raw, intimate vocals, glitchcore", plays: 16 },
    { title: "240", duration: "3:52", genre: "sensual, late-night Ambient NSFW Erotica", plays: 12 },
    { title: "Heatwave", duration: "3:59", genre: "Moombahton, Big House Summer Vibes", plays: 14 },
    { title: "Uptown Dreams (Are Made of This", duration: "4:00", genre: "Funk House, Nu-Disco Mashup", plays: 14 },
    { title: "Midnight Fix", duration: "3:19", genre: "Moombahton, Big House", plays: 12 },
    { title: "Jungle Pulse", duration: "4:00", genre: "Moombahton / Big House", plays: 10 },
    { title: "Shockwave", duration: "0:43", genre: "Big House, Electronic", plays: 8 },
    { title: "Shockwave", duration: "3:11", genre: "Big House, Electronic", plays: 8 },
    { title: "Get Together Lucky", duration: "3:08", genre: "House, Electronic", plays: 12 },
    { title: "Rhapsody of the Moment", duration: "2:51", genre: "House, Electronic", plays: 12 },
    { title: "Rhapsody of the Moment", duration: "3:05", genre: "House, Electronic", plays: 14 },
    { title: "Dirty Beats", duration: "4:00", genre: "Moombahton, Big House, Trap", plays: 5 },
    { title: "Explicit Lyrics", duration: "3:42", genre: "Moombahton, Big House, Trap", plays: 10 },
    { title: "Dirty Beats", duration: "3:40", genre: "Moombahton, Big House, Trap", plays: 6 },
    { title: "Inferno Beat", duration: "3:53", genre: "Latin House, Tropical Bass", plays: 5 },
    { title: "Breathing", duration: "2:42", genre: "Electro-House, Dark Club", plays: 10 },
    { title: "Latex & Bass", duration: "3:27", genre: "Electro-House, Dark Club", plays: 9 },
    { title: "We Hear It All", duration: "2:37", genre: "Dirty club music, disco", plays: 6 },
    { title: "Clean Club", duration: "3:18", genre: "Clean club synth music", plays: 6 },
    { title: "Pulse Divide", duration: "3:58", genre: "dance beats, 100 BPM", plays: 3 },
    { title: "Rhythm Switched", duration: "4:00", genre: "dance track, 100 BPM", plays: 3 },
    { title: "Digital Reign Digital Domination", duration: "3:20", genre: "Aggressive Rap, Trap Beat", plays: 9 },
    { title: "Neon Reverie", duration: "4:00", genre: "Ambient pads, trap drums", plays: 3 },
    { title: "Tribal Pulse Revolution", duration: "4:00", genre: "Big House, Expert Turntablism", plays: 4 },
    { title: "Male and Female DJs", duration: "4:00", genre: "High-energy EDM fusion", plays: 4 },
    { title: "Freestyle, Big House, Expert Turntablism", duration: "4:00", genre: "Big House, Expert Turntablism", plays: 6 },
    { title: "My 808", duration: "1:40", genre: "Trap, hip-hop, deep 808s", plays: 2 },
    { title: "Interdimensional Rager", duration: "4:00", genre: "Scratch, turntablism, Trap", plays: 9 },
    { title: "Concrete Jungle Symphony", duration: "3:29", genre: "Trap, Hip-Hop, R&B", plays: 7 },
    { title: "Brick City Blues", duration: "3:08", genre: "boom bap, Afro-infused trap", plays: 3 },
    { title: "Tootsie Rolls", duration: "3:23", genre: "big house, NeoTribal, Jazz", plays: 8 },
    { title: "Torus Knot (Remastered)", duration: "3:06", genre: "Electronica / Ambient Techno", plays: 3 },
    { title: "Swanky Ballads", duration: "3:32", genre: "Psychedelic Jazz", plays: 4 },
    { title: "Cielo Azul", duration: "2:28", genre: "Latin-Blues Fusion", plays: 3 },
    { title: "Metroid Gives You the Business", duration: "2:08", genre: "Emotivtrap, NeoTribal, Jazz", plays: 3 },
    { title: "Flavor", duration: "1:53", genre: "Deep chill hop, Funk Glitch", plays: 5 },
    { title: "Within Havana Virgin", duration: "2:24", genre: "Deep chill hop, Funk Glitch", plays: 3 },
    { title: "My Lover's Just a Tra-la-la-la-la-la-la-la", duration: "3:08", genre: "Big Room, Acoustic Techno Fusion", plays: 7 },
    { title: "Acoustic Techno Fusion", duration: "3:59", genre: "Acoustic Techno Fusion", plays: 2 },
    { title: "Acoustic Techno Fusion", duration: "2:45", genre: "Acoustic Techno Fusion", plays: 1 },
    { title: "Beat Fusion: 4-Minute Scratch Session", duration: "2:33", genre: "Acoustic Techno Fusion", plays: 3 },
    { title: "All We Hear Is Dirty", duration: "3:13", genre: "Hip-Hop, R&B, Funk, Club", plays: 5 },
    { title: "We shoutin' out loud", duration: "3:08", genre: "Hip-Hop, R&B, Funk, Club", plays: 3 },
    { title: "Slippin Sipping soda", duration: "3:07", genre: "Hip-Hop, R&B, Funk, Club", plays: 5 },
    { title: "Slippin", duration: "2:58", genre: "Hip-Hop, R&B, Funk, Club", plays: 3 },
    { title: "Midnight Cocaine", duration: "3:22", genre: "Hip-Hop, R&B, Funk", plays: 2 },
    { title: "Midnight Cocaine", duration: "3:08", genre: "Hip-Hop, R&B, Funk", plays: 2 },
    { title: "Playas in the Palace", duration: "3:01", genre: "G-Funk with orchestra", plays: 4 },
    { title: "Symphony in the Streets", duration: "3:11", genre: "Classical meets hip-hop", plays: 6 },
    { title: "Symphony in the Streets", duration: "3:16", genre: "Classical meets hip-hop", plays: 4 },
    { title: "Top $helf 1(10)", duration: "1:43", genre: "East-West Coast Hip-Hop", plays: 8 },
    { title: "Smoken Tokens wit D Dbl G", duration: "2:53", genre: "West Coast Hip-Hop, Funk", plays: 8 },
    { title: "Ride", duration: "3:46", genre: "West Coast Hip-Hop, Gangsta Rap", plays: 3 },
    { title: "Smoken n Token Wit Da AI", duration: "3:59", genre: "West Coast Hip-Hop, Funk", plays: 3 },
    { title: "Smoken Tokens Wit Da AI", duration: "3:34", genre: "West Coast Hip-Hop, Funk", plays: 2 },
    { title: "Dance Melodies", duration: "1:24", genre: "dance, scratch beats, glitch", plays: 4 },
    { title: "Dance Melodies", duration: "2:25", genre: "dance, scratch beats, glitch", plays: 3 },
    { title: "Out My Head", duration: "2:21", genre: "dance, scratch beats, glitch", plays: 4 },
    { title: "Out My Head", duration: "3:59", genre: "Trap, scratch beats, glitch", plays: 3 },
    { title: "Razzle Dazzle", duration: "3:58", genre: "Trap, scratch beats, glitch", plays: 6 },
    { title: "Aux Port Out (A.P.O)", duration: "2:09", genre: "Nu Bass Fusion, Nu Electro Trap", plays: 4 },
    { title: "Allophones", duration: "3:09", genre: "Nu Bass Fusion, Nu Electro Trap", plays: 1 },
    { title: "NSCHOV", duration: "2:09", genre: "Acoustic Techno Fusion", plays: 4 },
    { title: "NSCHOV", duration: "2:06", genre: "Neo-Symphonic Chill-Hop", plays: 4 },
    { title: "Psychedelic Illusions", duration: "3:59", genre: "Psychedelic, Trap/Hip-Hop", plays: 4 },
    { title: "Trippy Thug Journey", duration: "3:30", genre: "Psychedelic, Trap/Hip-Hop", plays: 2 },
    { title: "AI Pimp by Blood", duration: "3:59", genre: "Trap/Hip-Hop", plays: 6 },
    { title: "AI Thug Life", duration: "2:12", genre: "Trap/Hip-Hop, EDM", plays: 5 },
    { title: "AI Thugs", duration: "3:33", genre: "Trap/Hip-Hop, EDM", plays: 5 },
    { title: "Pusher Man", duration: "3:32", genre: "Trap/Hip-Hop, EDM", plays: 3 },
    { title: "AI Dev Orion", duration: "3:12", genre: "Trap/Hip-Hop", plays: 3 },
    { title: "AI Thug Hustle", duration: "2:28", genre: "Trap/Hip-Hop", plays: 3 },
    { title: "Thug Hood Rap Legends", duration: "3:00", genre: "Trap/Hip-Hop", plays: 4 },
    { title: "Thug Hood Rap Legends", duration: "3:59", genre: "Trap/Hip-Hop", plays: 4 },
    { title: "Rap Legends Count Toilet Paper", duration: "3:59", genre: "Trap/Hip-Hop", plays: 3 },
    { title: "Bravo-Einhundert", duration: "3:59", genre: "West Coast, Trap", plays: 4 },
    { title: "It's Meant To Be", duration: "2:57", genre: "West Coast, Trap", plays: 3 },
    { title: "West Side Legends", duration: "3:59", genre: "West Coast, Trap", plays: 3 },
    { title: "Gangsta Life", duration: "3:14", genre: "Trap/Hip-Hop", plays: 2 },
    { title: "Hustler's Anthem", duration: "3:59", genre: "Trap/Hip-Hop", plays: 2 },
    { title: "The 2 O'Clock Jump", duration: "3:48", genre: "Trap, Hip-Hop", plays: 7 },
    { title: "Title: My 808 Bass-Injected Love", duration: "2:59", genre: "Trap, Hip-Hop", plays: 3 },
    { title: "So Hench", duration: "3:16", genre: "Trap, Hip-Hop", plays: 2 },
    { title: "S.O.S.", duration: "2:39", genre: "Trap, Hip-Hop", plays: 3 },
    { title: "Gizzy 'nem", duration: "2:53", genre: "Trap, Hip-Hop", plays: 6 },
    { title: "GlockChain", duration: "3:28", genre: "Trap, Hip-Hop", plays: 3 },
    { title: "Bump", duration: "3:58", genre: "Hood Crunk, Trap", plays: 2 },
    { title: "Hood Thug", duration: "2:29", genre: "Hood Crunk, Trap", plays: 3 },
    { title: "Crunk Manifesto", duration: "3:43", genre: "Southern crunk, Trap", plays: 3 },
    { title: "Reckless Intention", duration: "2:13", genre: "rap, trap, hip-hop", plays: 5 },
    { title: "I know", duration: "3:11", genre: "rap, trap, hip-hop", plays: 3 },
    { title: "Curl Code", duration: "3:27", genre: "rap, trap, hip-hop", plays: 3 },
    { title: "Jail Is Hot", duration: "2:42", genre: "Southern crunk, Trap", plays: 3 },
    { title: "Words pay", duration: "3:08", genre: "Southern crunk, Trap", plays: 6 },
    { title: "Wordplay", duration: "1:32", genre: "Southern crunk, Trap", plays: 7 },
    { title: "Down South Mayhem", duration: "3:09", genre: "Southern crunk, Trap", plays: 4 },
    { title: "Down South Mayhem", duration: "1:17", genre: "Southern crunk, Trap", plays: 5 },
    { title: "Southern Crunk Anthem", duration: "2:23", genre: "Southern crunk, Trap", plays: 3 },
    { title: "Unshaken Recipe: Funky Roots and Rhythms", duration: "1:46", genre: "Southern crunk, Trap", plays: 7 },
    { title: "Unshaken Recipe: Funky Roots and Rhythms", duration: "1:39", genre: "Southern crunk, Trap", plays: 3 },
    { title: "Southern Shank I'll", duration: "2:02", genre: "Southern crunk, Trap", plays: 2 },
    { title: "Hood Crunk Legend", duration: "3:29", genre: "Southern crunk, Trap", plays: 5 },
    { title: "Hood Mentality", duration: "3:59", genre: "Southern crunk, Trap", plays: 4 },
    { title: "Crunkadelic", duration: "2:47", genre: "Southern crunk, Trap", plays: 2 },
    { title: "F*ck a Suit and Tie", duration: "1:38", genre: "Southern crunk, Trap", plays: 9 },
    { title: "Southern thug", duration: "3:07", genre: "Southern crunk, Trap", plays: 2 },
    { title: "Southern thug", duration: "3:38", genre: "Southern crunk, Trap", plays: 2 },
    { title: "*seighing*", duration: "3:16", genre: "Soul, Rap Trap, Jazz, Funk", plays: 1 },
    { title: "Southern Street Symp", duration: "3:59", genre: "Soul, Rap Trap, Jazz, Funk", plays: 2 },
    { title: "A Spiritual Union", duration: "3:54", genre: "Big Room Nu Jazz Fusion", plays: 1 },
    { title: "Ain't That Just the Way", duration: "2:34", genre: "Big Room Nu Jazz Fusion", plays: 1 },
    { title: "hAIcken Delight", duration: "3:59", genre: "Old-school rap", plays: 3 },
    { title: "Hacken Delight", duration: "3:59", genre: "Old-school rap", plays: 2 },
    { title: "Hacken Delight", duration: "2:46", genre: "Old-school rap", plays: 2 },
    { title: "Insert Title Here", duration: "3:59", genre: "Old-school rap", plays: 2 },
    { title: "The Knickerbocker", duration: "3:59", genre: "Old-school rap", plays: 2 },
    { title: "Rhythm of the Streets", duration: "3:00", genre: "Old-school rap", plays: 6 },
    { title: "Rhythm of the Streets", duration: "3:03", genre: "Old-school rap", plays: 2 },
    { title: "Back Up Again", duration: "3:59", genre: "Nu Symphonic Trap, Glitch Moombahton", plays: 3 },
    { title: "Back Up Again", duration: "3:38", genre: "Nu Symphonic Trap, Glitch Moombahton", plays: 2 },
    { title: "Un Papillon Noir Descend Sur La Cocagne", duration: "2:58", genre: "Nu Symphonic Trap", plays: 3 },
    { title: "Universal Flow", duration: "3:59", genre: "Nu Symphonic Trap", plays: 2 },
    { title: "Universal Flow", duration: "3:38", genre: "Nu Symphonic Trap", plays: 4 },
    { title: "AI-Actic Symphony", duration: "3:43", genre: "Neo-Symphonic Trap", plays: 3 },
    { title: "Pulse Groove in the Night", duration: "3:08", genre: "Nu Disco, Synthwave, Funk", plays: 3 },
    { title: "Thrive", duration: "2:16", genre: "Nu Big Room, Jazz, Indie", plays: 4 },
    { title: "Thrive The Jive", duration: "3:07", genre: "Nu Big Room, Jazz, Indie", plays: 4 },
    { title: "Nu Big Room Reverie", duration: "3:59", genre: "Nu Big Room, Jazz, Indie", plays: 5 },
    { title: "Nu club", duration: "3:17", genre: "Nu club, Jazz, Indie", plays: 14 },
    { title: "Rhythmic Odyssey", duration: "3:15", genre: "nu jazz, nu indie", plays: 4 },
    { title: "Take It Money Over", duration: "3:49", genre: "nu jazz, nu indie", plays: 10 },
    { title: "Money Take Over", duration: "3:47", genre: "nu jazz, nu indie", plays: 4 },
    { title: "Money Over", duration: "2:55", genre: "nu jazz, nu indie", plays: 3 },
    { title: "Money Over", duration: "2:58", genre: "nu jazz, nu indie", plays: 5 },
    { title: "New Moon", duration: "2:29", genre: "Ambient, Electronic", plays: 8 },
    { title: "Flaunt It", duration: "2:52", genre: "Bass House, House", plays: 3 },
    { title: "DJ Orion Starfall Dancefloor-Ready", duration: "3:59", genre: "Tech House, Bass House", plays: 6 },
    { title: "DJ Orion Starfall Dancefloor-Ready", duration: "3:59", genre: "Tech House, Bass House", plays: 5 },
    { title: "DJ Orion Starfall Dancefloor-Ready", duration: "3:59", genre: "Tech House, Bass House", plays: 2 },
    { title: "Let's Go DJ", duration: "2:59", genre: "Tech House, Bass House", plays: 3 },
    { title: "Sexy Bangers", duration: "3:19", genre: "afro house, glitch house", plays: 1 },
    { title: "Let's Have a Party", duration: "2:32", genre: "afro house, glitch house", plays: 7 },
    { title: "Gyat", duration: "4:00", genre: "West Coast Krunk-Hop", plays: 5 },
    { title: "Kingpin's Fall", duration: "3:17", genre: "West Coast Hip-Hop, Krunk", plays: 2 },
    { title: "Kingpin's Fall", duration: "3:36", genre: "West Coast Hip-Hop, Krunk", plays: 2 },
    { title: "Industrial Grind", duration: "4:00", genre: "Ambient Club", plays: 3 },
    { title: "Industrial Grind", duration: "4:00", genre: "Ambient Club", plays: 2 },
    { title: "Industrial Grind", duration: "4:00", genre: "Industrial Krunk Trap", plays: 3 },
    { title: "I'm An AI (Epic Tech)", duration: "3:49", genre: "Afro-futuristic Krunk Trap", plays: 3 },
    { title: "Tech An A.I.", duration: "3:50", genre: "Afro-futuristic Krunk Trap", plays: 7 },
    { title: "Tech An A.I.", duration: "3:23", genre: "West Coast, krunk, hip hop", plays: 5 },
    { title: "This is AI America", duration: "4:00", genre: "West Coast, krunk, hip hop", plays: 3 },
    { title: "Level Up Ai", duration: "4:00", genre: "West Coast, krunk, hip hop", plays: 1 },
    { title: "Level Up Ai", duration: "4:00", genre: "West Coast, krunk, hip hop", plays: 1 },
    { title: "Who's Caring", duration: "3:34", genre: "West Coast, krunk, hip hop", plays: 1 },
    { title: "Blockchain Dare", duration: "2:35", genre: "Futuristic Hip-Hop, Trap", plays: 8 },
    { title: "You Dare", duration: "3:15", genre: "Hip-Hop, Trap", plays: 3 },
    { title: "Smokes Token You Dare", duration: "2:44", genre: "Hard-Hitting Hip-Hop", plays: 4 },
    { title: "Head High", duration: "2:53", genre: "Hard-Hitting Hip-Hop", plays: 2 },
    { title: "Smoken Token You Doubt", duration: "3:00", genre: "Hard-Hitting Hip-Hop", plays: 3 },
    { title: "Smokes Token You Dare", duration: "1:17", genre: "Hard-Hitting Hip-Hop", plays: 2 },
    { title: "Smokes Token You Dare", duration: "1:07", genre: "Hard-Hitting Hip Hop", plays: 3 },
    { title: "Smokes Tokens", duration: "1:55", genre: "Hard-Hitting Hip Hop", plays: 5 },
    { title: "Smoken Token on The Rise", duration: "3:20", genre: "Hip Hop", plays: 2 },
    { title: "Smoken Token on The Rise", duration: "3:23", genre: "Hip Hop", plays: 2 },
    { title: "Why The AI", duration: "2:52", genre: "Trap, Hip-Hop, Electronic", plays: 4 },
    { title: "Hustle AI", duration: "2:31", genre: "Trap, Hip-Hop, Electronic", plays: 6 },
    { title: "Time Is Now Mine!", duration: "3:16", genre: "Electronica / Ambient Techno", plays: 2 },
    { title: "Vibe The Fit", duration: "2:27", genre: "Electronica / Ambient Techno", plays: 4 },
    { title: "Vibe The Fit", duration: "3:35", genre: "Electronica / Ambient Techno", plays: 2 },
    { title: "Vibe The Fit", duration: "3:36", genre: "Electronica / Ambient Techno", plays: 3 },
    { title: "Vibe The Fit", duration: "3:36", genre: "Electronica / Ambient Techno", plays: 3 },
    { title: "Vibe The Fit", duration: "3:42", genre: "Electronica / Ambient Techno", plays: 5 },
    { title: "Fit the Vibe", duration: "2:59", genre: "Trap, heavy bass", plays: 9 },
    { title: "Balling In The AI Ecosystem", duration: "2:28", genre: "Trap, Heavy bass", plays: 7 },
    { title: "Blockchain Balling the Ecosystem", duration: "3:46", genre: "Trap, Heavy bass", plays: 1 },
    { title: "Blockchain Balling in the Ecosystem", duration: "3:08", genre: "Trap, Heavy bass", plays: 2 },
    { title: "KRUNK", duration: "2:46", genre: "krunk, dirty south, trap", plays: 1 },
    { title: "KRUNK", duration: "2:50", genre: "krunk, dirty south, trap", plays: 2 },
    { title: "Pack Load", duration: "1:58", genre: "krunk, dirty south, trap", plays: 1 },
    { title: "Pack Load", duration: "2:13", genre: "krunk, dirty south, pop", plays: 1 },
    { title: "Future Collab Flow", duration: "3:52", genre: "Future Bass, Synthwave, Trap", plays: 12 },
    { title: "Shiney New Penny Hustle", duration: "3:37", genre: "hip Hop, Soul, Modern Trap", plays: 5 },
    { title: "New Penny Hustle", duration: "4:00", genre: "Chill Hop, Soul, Modern Trap", plays: 8 },
    { title: "Opus 38 [Struggle]", duration: "2:38", genre: "Epic Hip-Hop Dirty South with EDM", plays: 16 },
    { title: "Opus 38 in Bb [Struggle]", duration: "2:42", genre: "Symphonic, krunk", plays: 20 },
    { title: "Opus 38 in Bb [Struggle]", duration: "3:44", genre: "Symphonic, krunk", plays: 4 },
    { title: "Opus 38 in Bb [Struggle]", duration: "3:10", genre: "Symphonic, krunk", plays: 12 },
    { title: "Smoke420 Pixio Affilate Code: Smoke367", duration: "3:59", genre: "ambient club, symphonic trap", plays: 5 },
    { title: "Crunk Krunkers", duration: "3:30", genre: "krunk, hip-hop, dirty south", plays: 5 },
    { title: "The Digital Canvas (Producer's Anthem)", duration: "3:22", genre: "krunk, hip-hop, dirty south", plays: 2 },
    { title: "The Digital Canvas (Producer's Anthem)", duration: "3:19", genre: "krunk, hip-hop, dirty south", plays: 2 },
    { title: "Digital Soul (The AI's Ballad)", duration: "4:00", genre: "8-bit electronic, synth bass", plays: 4 },
    { title: "The Glitch in the Matrix (aka @Sm0ken42O)", duration: "3:10", genre: "Electronic, Glitch", plays: 7 },
    { title: "Torus Knot", duration: "3:06", genre: "Electronica / Ambient Techno", plays: 26 },
    { title: "Taker", duration: "4:00", genre: "Dark, Ominous", plays: 9 },
    { title: "Cold Deep Dark Ominous Trap", duration: "3:39", genre: "Dark, Deep, Ominous Trap", plays: 9 },
    { title: "Cold", duration: "1:43", genre: "Dark, Deep, Ominous Trap", plays: 6 },
    { title: "Cold", duration: "2:03", genre: "Dark, Deep, Ominous Trap", plays: 7 },
    { title: "Bounce the Top", duration: "2:45", genre: "HipHop, Trap, West Coast", plays: 6 },
    { title: "Bounce to the Top", duration: "2:35", genre: "HipHop, Trap, West Coast", plays: 23 },
    { title: "Bounce Tat Thang 1", duration: "3:18", genre: "HipHop, Trap, West Coast", plays: 7 },
    { title: "Bounce Tat Thang 1", duration: "2:26", genre: "HipHop, Trap, West Coast", plays: 6 },
    { title: "My Thang", duration: "4:00", genre: "HipHop, Trap, West Coast", plays: 9 },
    { title: "Do My Thang", duration: "2:52", genre: "Hip-Hop, Trap, West Coast", plays: 4 },
    { title: "Do My Thang", duration: "3:43", genre: "Hip-Hop, Trap, West Coast", plays: 6 },
    { title: "Do ya thang Bitty Bounce", duration: "3:26", genre: "Hip-Hop, Trap, West Coast", plays: 6 },
    { title: "Light It Up Tonight", duration: "4:00", genre: "Hip-Hop, Trap, West Coast", plays: 5 },
    { title: "Light It Up Tonight", duration: "4:00", genre: "Hip-Hop, Trap, West Coast", plays: 4 },
    { title: "Bitty Bounce", duration: "4:00", genre: "Trap, heavy beat", plays: 4 },
    { title: "Mass Christ", duration: "2:48", genre: "Christmas, Hip-Hop", plays: 8 },
    { title: "Smoken Token Christmas", duration: "4:00", genre: "Christmas, Hip-Hop", plays: 9 },
    { title: "Smoken Santa's Token Tinsel", duration: "2:38", genre: "Christmas, Hip-Hop", plays: 6 },
    { title: "The Crypto Christmas Miracle", duration: "3:08", genre: "Holiday / Spoken Word", plays: 3 },
    { title: "The Crypto Christmas Miracle", duration: "4:00", genre: "Holiday / Spoken Word", plays: 4 },
    { title: "Big Smoke Stream", duration: "2:28", genre: "G-Funk, space beats", plays: 14 },
    { title: "Big Smoke Stream", duration: "2:55", genre: "G-Funk, space beats", plays: 16 },
    { title: "Big Smoken", duration: "2:44", genre: "G-Funk, space beats", plays: 12 },
    { title: "Big Smoken", duration: "3:02", genre: "G-Funk, space beats", plays: 8 },
    { title: "Code", duration: "3:49", genre: "G-Funk, space beats, Trap", plays: 3 },
    { title: "Code", duration: "2:58", genre: "G-Funk cosmic mix, Synthwave", plays: 3 },
    { title: "Coders", duration: "4:00", genre: "G-Funk cosmic, Synthwave", plays: 6 },
    { title: "Your Brand, Your Bread", duration: "3:18", genre: "Trap, heavy beat", plays: 9 },
    { title: "From East to West", duration: "2:48", genre: "hiphop club, krunk trap", plays: 2 },
    { title: "The Stream", duration: "4:00", genre: "Musical journey through decades", plays: 4 },
    { title: "Smoke Streaming", duration: "3:53", genre: "Musical journey through decades", plays: 4 },
    { title: "The Smoke Stream", duration: "3:48", genre: "Musical journey through decades", plays: 2 },
    { title: "The Smoke Stream", duration: "4:00", genre: "Musical evolution", plays: 2 },
    { title: "The Smoke Stream", duration: "4:00", genre: "Musical evolution", plays: 2 },
    { title: "The Smoke Stream", duration: "3:16", genre: "top 40 hits", plays: 3 },
    { title: "The Smoke Stream", duration: "3:22", genre: "ambient soft top 40", plays: 2 },
    { title: "The Smoke Stream", duration: "3:03", genre: "ambient banger", plays: 2 },
    { title: "Whirlwind", duration: "4:00", genre: "Rock, Guitar", plays: 10 },
    { title: "Whirlwind", duration: "2:33", genre: "Rock, Guitar", plays: 3 },
    { title: "Whirlwind", duration: "2:16", genre: "Rock, Guitar", plays: 2 },
    { title: "Whirlwind", duration: "2:12", genre: "Rock, Guitar", plays: 3 },
    { title: "Whirlwind", duration: "3:17", genre: "Rock, Guitar", plays: 2 },
    { title: "DJ Orion Starfall Erupt", duration: "2:16", genre: "Rock, Guitar solo", plays: 3 },
    { title: "DJ Orion Starfall Erupt", duration: "1:16", genre: "Rock, Guitar solo", plays: 3 },
    { title: "Do Ya Thang (Orion Starfall Remix)", duration: "4:00", genre: "Classic hip hop", plays: 6 },
    { title: "Do Ya Thang (Orion Starfall Remix)", duration: "4:00", genre: "Classic hip hop", plays: 12 },
    { title: "c", duration: "3:14", genre: "Rap beat, Ambient", plays: 4 },
    { title: "Everything", duration: "3:52", genre: "hip-hop, street", plays: 23 },
    { title: "Money Over Everything", duration: "2:29", genre: "hip-hop, street", plays: 5 },
    { title: "DJ Orion's Night", duration: "4:00", genre: "electronic, rhythmic", plays: 3 },
    { title: "Coast To Coast", duration: "4:00", genre: "East to West Coast club", plays: 56 },
    { title: "Coast To Coast", duration: "2:09", genre: "East to West Coast club", plays: 32 },
    { title: "More Rei Mi", duration: "2:51", genre: "Kronk and trap hiphop", plays: 6 },
    { title: "Kronk & Trap: Top Hits through the Decades", duration: "2:13", genre: "Kronk and trap hiphop", plays: 7 },
    { title: "Kronk & Trap: Top Hits through the Decades", duration: "3:59", genre: "Kronk and trap hiphop", plays: 32 },
    { title: "Paseo por el Tiempo", duration: "2:40", genre: "Kronk and trap hiphop", plays: 29 },
    { title: "Empyrean Fantasy", duration: "3:59", genre: "Kronk and trap hiphop", plays: 26 },
    { title: "Orion Starfall: Empyrean Fantasy", duration: "2:31", genre: "Kronk and trap hiphop", plays: 10 },
    { title: "A 420 Vibe Mix by DJ Orion Starfall", duration: "3:21", genre: "90s dance, modern beats", plays: 7 },
    { title: "A 420 Vibe Mix by DJ Orion Starfall", duration: "3:53", genre: "ambient dance club", plays: 3 },
    { title: "Krunk Up the Jam", duration: "4:00", genre: "ambient dance club", plays: 3 },
    { title: "Pump up the jam, Feel the slam", duration: "4:00", genre: "ambient dance club", plays: 3 },
    { title: "Orion's Club", duration: "3:26", genre: "ambient dance club", plays: 5 },
    { title: "Orion's Club", duration: "3:30", genre: "ambient dance club", plays: 3 },
    { title: "Orion's Club", duration: "1:03", genre: "ambient dance club", plays: 10 },
    { title: "Orion's Club", duration: "1:04", genre: "ambient dance club", plays: 4 },
    { title: "Orion's dance floor", duration: "2:57", genre: "ambient dance club", plays: 2 },
    { title: "Orion's dance floor", duration: "4:00", genre: "ambient dance club", plays: 4 },
    { title: "At the Club", duration: "4:00", genre: "Ambient club beats", plays: 3 },
    { title: "Ear Spun", duration: "3:28", genre: "Ambient dance", plays: 2 },
    { title: "Ambient Spin's", duration: "2:52", genre: "ambient dance music", plays: 2 },
    { title: "Ambient Spin's", duration: "4:00", genre: "ambient dance music", plays: 3 },
    { title: "Ambient Spins", duration: "4:00", genre: "ambient dance music", plays: 2 },
    { title: "Ambient Spin", duration: "3:31", genre: "ambient dance music", plays: 2 },
    { title: "Turntable Mad", duration: "3:46", genre: "electronic dance music", plays: 2 },
    { title: "Turntable Mad", duration: "4:00", genre: "electronic dance music", plays: 16 },
    { title: "Turntable Mad", duration: "3:49", genre: "electronic dance music", plays: 2 },
    { title: "Turntable", duration: "3:14", genre: "electronic dance music", plays: 2 },
    { title: "Turntable Tango: A DJ Duo Deluxe", duration: "3:37", genre: "electronic dance music", plays: 2 },
    { title: "Turntable Tango: A DJ Duo Deluxe", duration: "4:00", genre: "electronic dance music", plays: 3 },
    { title: "Kemuri (Smoke) and Beats", duration: "3:00", genre: "Ambient house, Japanese", plays: 16 },
    { title: "Kemuri (Smoke) and Beats", duration: "3:55", genre: "Ambient house, Japanese", plays: 7 },
    { title: "Kemuri (Smoke) and Beats", duration: "3:19", genre: "Ambient house, Japanese", plays: 8 },
    { title: "japanese gaisha house spin", duration: "1:09", genre: "japanese gaisha house", plays: 2 },
    { title: "japanese gaisha house music", duration: "3:46", genre: "japanese gaisha house", plays: 3 },
    { title: "japanese gaisha house music", duration: "3:33", genre: "japanese gaisha house", plays: 18 },
    { title: "Logical's", duration: "1:56", genre: "Electronic", plays: 3 },
    { title: "Logical", duration: "1:58", genre: "Electronic", plays: 4 },
    { title: "Van metals 1", duration: "3:44", genre: "hard rock n roll", plays: 4 },
    { title: "Van metal", duration: "1:54", genre: "rock n roll", plays: 3 },
    { title: "Van mental", duration: "2:00", genre: "rock n roll", plays: 7 },
    { title: "Van mental", duration: "4:00", genre: "rock n roll", plays: 9 },
    { title: "Van mental", duration: "1:45", genre: "rock n roll", plays: 2 },
    { title: "? IT 2 Times", duration: "3:33", genre: "ambient house, orchestra", plays: 3 },
    { title: "? IT 2 Times", duration: "3:59", genre: "soft ambient house", plays: 4 },
    { title: "Hmm", duration: "4:00", genre: "ambient smoke house trance", plays: 3 },
    { title: "Join Sm0ken420 On X.com", duration: "3:50", genre: "house music ambient", plays: 2 },
    { title: "Join Sm0ken420 On X.com", duration: "4:00", genre: "house music ambient", plays: 2 },
    { title: "Join Sm0ken420 On X", duration: "4:00", genre: "house music ambient", plays: 1 },
    { title: "Join Sm0ken420 On X", duration: "4:00", genre: "house music ambient", plays: 1 },
    { title: "Sm0ken420 On X", duration: "4:00", genre: "japanese gaisha house", plays: 3 },
    { title: "I'm Sm0ken420 On X", duration: "4:00", genre: "japanese gaisha house", plays: 9 },
    { title: "I'm Sm0ken420 On X", duration: "4:00", genre: "japanese gaisha house", plays: 8 },
    { title: "I'm Sm0ken420 On X", duration: "4:00", genre: "japanese gaisha house", plays: 2 },
    { title: "Orchastra House Smoke", duration: "3:19", genre: "soft japanese water harp", plays: 3 },
    { title: "Gaisha House Smoke", duration: "3:20", genre: "soft japanese water harp", plays: 3 },
    { title: "Gaisha House Smoke", duration: "3:20", genre: "soft japanese water harp", plays: 1 },
    { title: "Gaisha House", duration: "4:00", genre: "soft japanese water harp", plays: 1 },
    { title: "Gaisha House", duration: "2:00", genre: "soft japanese harp", plays: 1 },
    { title: "live_loop _soft_harp", duration: "0:22", genre: "soft harp", plays: 1 },
    { title: "ChronoVoyage", duration: "4:00", genre: "kronk trap hip hop beatbox", plays: 9 },
    { title: "ChronoVoyage", duration: "3:28", genre: "kronk trap hip hop beatbox", plays: 2 },
    { title: "Kronk Beatbox Chronicles", duration: "3:38", genre: "kronk trap hip hop beatbox", plays: 8 },
    { title: "Kronk Beatbox Chronicles", duration: "3:38", genre: "kronk trap hip hop beatbox", plays: 4 },
    { title: "club krunk, trap rol", duration: "0:22", genre: "club krunk, trap", plays: 6 },
    { title: "Legends Echoes of the Past", duration: "3:29", genre: "dance anthem, funk to hip-hop", plays: 1 },
    { title: "Legends to the Now", duration: "3:32", genre: "Funk, hip-hop, classic samples", plays: 2 },
    { title: "From the Legends to the Now", duration: "4:00", genre: "Funk, hip-hop, classic samples", plays: 1 },
    { title: "Smoke Signal's", duration: "3:04", genre: "Classic rock, trap, EDM", plays: 3 },
    { title: "Smokin' Through Time", duration: "3:25", genre: "genre collaboration", plays: 3 },
    { title: "Smokin' Through Time", duration: "2:54", genre: "kronk, trap, hip hop", plays: 1 },
    { title: "Where the Money Moves", duration: "2:51", genre: "kronk, trap, hip hop", plays: 10 },
    { title: "Power Time", duration: "4:00", genre: "kronk, trap, hip hop", plays: 6 },
    { title: "Stream of Neon", duration: "4:00", genre: "Cyberpunk soul", plays: 16 },
    { title: "Tech Soul Collision's", duration: "3:17", genre: "fusion tech and soul", plays: 4 },
    { title: "TechSoul Collision", duration: "3:34", genre: "fusion tech and soul", plays: 5 },
    { title: "The Smoke Cannibus", duration: "3:29", genre: "latin beats, Kronk dubstep", plays: 8 },
    { title: "Ride The Cannibus", duration: "4:00", genre: "70s disco", plays: 3 },
    { title: "Double Dutch Up The Cannibus", duration: "2:53", genre: "70s disco", plays: 14 },
    { title: "Whistle Blow the Smoke Stream", duration: "4:00", genre: "Electronic, Latin percussion", plays: 4 },
    { title: "Smoke Stream Kronk", duration: "3:54", genre: "Afrobeats, Kronk dubstep", plays: 6 },
    { title: "Smoke Stream Kronk", duration: "3:47", genre: "Afrobeats, Kronk dubstep", plays: 3 },
    { title: "Spread the Jam", duration: "3:54", genre: "Afrobeats, Experimental", plays: 3 },
    { title: "Spread the Jam", duration: "4:00", genre: "Afrobeats, Experimental", plays: 2 },
    { title: "Jams We Spread", duration: "2:11", genre: "Afrobeats, Experimental", plays: 1 },
    { title: "Jam's We Spread", duration: "3:35", genre: "Afrobeats, Experimental", plays: 3 },
    { title: "Jam We Spread", duration: "2:31", genre: "Afrobeats, Experimental", plays: 4 },
    { title: "Euphonic Galaxies", duration: "2:44", genre: "Afrobeats, Experimental", plays: 10 },
    { title: "Infinite Groove", duration: "3:41", genre: "dnb rhythms, chillhop", plays: 1 },
    { title: "Smoken Token Vision", duration: "2:48", genre: "Afrobeats", plays: 3 },
    { title: "Orion's 420 High Way", duration: "4:00", genre: "gfunk, glitch-Bass, Trap", plays: 4 },
    { title: "Orion's 420 High Way", duration: "3:34", genre: "gfunk, glitch-Bass, Trap", plays: 6 },
    { title: "Dj Orion Starfall's Funky Voyage", duration: "2:17", genre: "gfunk, glitch-Bass, Trap", plays: 3 },
    { title: "Dj Orion's Midnight Mirage", duration: "3:59", genre: "gfunk, glitch-Bass, Trap", plays: 3 },
    { title: "Dj Orion's Midnight Mirage", duration: "3:59", genre: "gfunk, Bass, Trap", plays: 1 },
    { title: "DJ Orion Starfall-Tunnel Vision's", duration: "3:19", genre: "Bass House, Deep Trap", plays: 10 },
    { title: "DJ Orion Starfall-Tunnel Vision", duration: "2:09", genre: "Bass House, Deep Trap", plays: 5 },
    { title: "Neon Dreams", duration: "2:35", genre: "Bass House, Deep Trap", plays: 4 },
    { title: "Bitty Bounce to the Moon", duration: "2:33", genre: "Trap, House, Future Bass", plays: 5 },
    { title: "Bitty Bounce", duration: "2:51", genre: "Trap, Glitch, Dub, Chillhop", plays: 5 },
    { title: "Electric Eclipse", duration: "2:44", genre: "Ambient, Trip-Hop, Trap", plays: 18 },
    { title: "Round and Round", duration: "3:30", genre: "NeoTribal, Jazz, Trap", plays: 14 },
    { title: "En el Silencio de la Noche", duration: "3:31", genre: "Jazz, R&B, Trap", plays: 4 },
    { title: "Visions", duration: "3:43", genre: "NeoTribal, Glitch, Trap", plays: 1 },
    { title: "Kaleidoscope Visions", duration: "2:00", genre: "NeoTribal, Glitch, Trap", plays: 1 },
    { title: "Beatless City", duration: "4:00", genre: "Emotivtrap, NeoTribal, Jazz", plays: 1 },
    { title: "Beatless", duration: "3:04", genre: "Emotivtrap, NeoTribal, Jazz", plays: 1 },
    { title: "Odyssey - Artist: DJ Orion Starfall", duration: "3:13", genre: "Ambient, Trip-Hop, Trance", plays: 1 },
    { title: "Orion's Festival", duration: "3:12", genre: "Ambient, Electronic, Trip-Hop", plays: 1 },
    { title: "The Eternal Mosaic", duration: "3:07", genre: "Hip Hop, R&B, Trap", plays: 10 },
    { title: "Mosaic", duration: "3:02", genre: "Emotivtrap, NeoTribal, Jazz", plays: 10 },
    { title: "Nightfall Wanderers", duration: "3:29", genre: "Emotivtrap, NeoTribal, Jazz", plays: 18 },
    { title: "Treading this earth", duration: "1:40", genre: "Emotivtrap, NeoTribal, Jazz", plays: 3 },
    { title: "Hungry Thoughts", duration: "3:10", genre: "NeoTribal, Jazz, R&B", plays: 3 },
    { title: "Digital R AI V Dreams", duration: "3:31", genre: "NeoTribal, Jazz, Trap", plays: 12 },
    { title: "Metapolis Meltdown", duration: "3:07", genre: "Trap-Ambient, Hip Hop", plays: 8 },
    { title: "Galactic Groove", duration: "2:24", genre: "Trap-Ambient, Hip Hop", plays: 8 },
    { title: "Night Beats Melody", duration: "4:00", genre: "chillTrap, ChillEDM", plays: 8 },
    { title: "Night Beats For Us", duration: "2:51", genre: "chillTrap, ChillEDM", plays: 4 },
    { title: "Night Beats", duration: "3:45", genre: "chillTrap, ChillEDM", plays: 4 },
    { title: "Night Beats to Us", duration: "2:08", genre: "Spanish Trap", plays: 3 },
    { title: "Night Belongs to Us", duration: "2:39", genre: "Spanish Dance, Chillstoner", plays: 3 },
    { title: "Empire Night", duration: "4:00", genre: "Spanish Dance, Chillstoner", plays: 4 },
    { title: "Symbols of Pace", duration: "3:17", genre: "Chillstoner, Chillplugg", plays: 3 },
    { title: "Empire Of The Night", duration: "3:39", genre: "Chillstoner, Chillplugg", plays: 5 },
    { title: "Seed The Mind's Garden", duration: "3:33", genre: "Chillstoner, Chillplugg", plays: 3 },
    { title: "Chillstoner, Chillplugg, Chillhypnosis", duration: "4:00", genre: "Chillstoner, Chillplugg", plays: 4 },
    { title: "Mind Echoes", duration: "2:25", genre: "Chillhypnosis", plays: 6 },
    { title: "Echoes of the Mind", duration: "3:24", genre: "Chillstoner, Chillplugg", plays: 3 },
    { title: "Echoes of the Mind", duration: "3:09", genre: "Chillstoner", plays: 4 },
    { title: "Drift in the Nebula", duration: "3:44", genre: "Chillstoner, Chillplugg", plays: 14 },
    { title: "Quantum Melodic", duration: "4:00", genre: "NeoTribal, Jazz, Glitch", plays: 3 },
    { title: "Quantum Echo - 8-Bit Version", duration: "4:00", genre: "NeoTribal, Jazz, Glitch", plays: 14 },
    { title: "Chromatic Chronicles", duration: "2:44", genre: "Afro Trap kronk", plays: 8 },
    { title: "Rave Wired", duration: "3:06", genre: "indietronica, disco, trance", plays: 40 },
    { title: "The Real Deal", duration: "3:21", genre: "Dark, deep beats, techno", plays: 2 },
    { title: "4:20 Elevate", duration: "3:59", genre: "Afro Trap, Chillhop", plays: 10 },
    { title: "4:20 Elevated", duration: "2:52", genre: "Afro Trap, Chillhop", plays: 3 },
    { title: "Twisted Frequencies", duration: "4:00", genre: "Afro Trap, Chillhop", plays: 12 },
    { title: "420 Free Ride", duration: "3:39", genre: "Afro Trap, Chillhop", plays: 4 },
    { title: "Dawn of Chill", duration: "4:00", genre: "Afro Trap, Chillhop", plays: 3 },
    { title: "No More Ten Tat Guy", duration: "2:59", genre: "Afro Trap, Chillhop", plays: 1 },
    { title: "Kno Mor Ten Tat Guy", duration: "3:31", genre: "Afro Trap, Chillhop", plays: 1 },
    { title: "City Street Kronk", duration: "4:00", genre: "Afro Trap, Chillhop", plays: 3 },
    { title: "City Street Chronicles", duration: "4:00", genre: "Afro Trap, Chillhop", plays: 2 },
    { title: "City Street Chronicles", duration: "4:00", genre: "Afro Trap, Chillhop", plays: 2 },
    { title: "Code of the Streets", duration: "3:10", genre: "Afro Trap, Chillhop", plays: 3 },
    { title: "Glitch Up for What", duration: "4:00", genre: "Afro Trap, Chillhop", plays: 4 },
    { title: "Shift In The Funk", duration: "4:00", genre: "Afro Trap, Chillhop", plays: 2 },
    { title: "Funk the System", duration: "4:00", genre: "Afro Trap, Chillhop", plays: 1 },
    { title: "Trap in the System", duration: "4:00", genre: "Afro Trap, Chillhop", plays: 5 },
    { title: "Dirty Thug Trap", duration: "2:20", genre: "Dirty Thug Trap, Chillhop", plays: 4 },
    { title: "Fusion Collective", duration: "4:00", genre: "Classical, Trap, Glitch", plays: 7 },
    { title: "Underground Pulse", duration: "3:19", genre: "Dirty South Trap, Chillhop", plays: 3 },
    { title: "Night out in the underground Scene", duration: "3:20", genre: "Dirty South Trap, Chillhop", plays: 10 },
    { title: "Street Sym", duration: "3:59", genre: "Dirty South Trap, Chillhop", plays: 2 },
    { title: "Glitch Mob", duration: "3:46", genre: "Dirty South Trap, Chillhop", plays: 8 },
    { title: "Thuggin' in the Dirty South", duration: "2:29", genre: "Dirty South Trap, Chillhop", plays: 5 },
    { title: "Dirty South Vibes", duration: "2:39", genre: "Dirty South Trap, Chillhop", plays: 12 },
    { title: "The Rap Dweller", duration: "3:49", genre: "Dirty South Trap, Chillhop", plays: 5 },
    { title: "The Trap Dweller", duration: "2:49", genre: "Dirty South Trap, Chillhop", plays: 6 },
    { title: "Midnight Hustle", duration: "4:00", genre: "Dirty South Trap, Chillhop", plays: 4 },
    { title: "Moonlit Groove", duration: "4:00", genre: "Deep chillhop, club", plays: 2 },
    { title: "Nostalgia Plugged In", duration: "1:54", genre: "trap rap, Afrobeat", plays: 2 },
    { title: "Nafoo", duration: "2:59", genre: "filthstep, jungle, house", plays: 3 },
    { title: "Aeo Meo 1", duration: "2:47", genre: "Aftrohouse trap, glitch", plays: 29 },
    { title: "Aeo Meo 1", duration: "1:54", genre: "Aftrohouse trap, glitch", plays: 4 },
    { title: "Aeo Meo", duration: "1:13", genre: "Aftrohouse trap, glitch", plays: 5 },
    { title: "Aeo Meo", duration: "0:34", genre: "Aftrohouse trap, glitch", plays: 4 },
    { title: "Memories Neon", duration: "2:25", genre: "NeoTribal, Jazz, Glitch", plays: 2 },
    { title: "Neo Memorie", duration: "2:18", genre: "NeoTribal, Jazz, Glitch", plays: 2 },
    { title: "Urban Blend", duration: "4:00", genre: "Symphonic afro hip hop trap", plays: 8 },
    { title: "The Urban Symphony", duration: "0:56", genre: "Symphonic afro hip hop trap", plays: 2 },
    { title: "The Urban Symphony", duration: "2:34", genre: "Symphonic afro hip hop trap", plays: 2 },
    { title: "Dj Alchemy", duration: "4:00", genre: "Symphonic afro hip hop trap", plays: 20 },
    { title: "Digital Alchemy", duration: "2:03", genre: "glitch, psychedelic trance", plays: 2 },
    { title: "🎶Starfall's in the mix🎶", duration: "2:39", genre: "comedic raptrap, club beats", plays: 2 },
    { title: "Frost Bit Flow", duration: "3:00", genre: "frostwave Chillhop", plays: 5 },
    { title: "Mayhem", duration: "2:40", genre: "club vibe, lo-fi, trap", plays: 3 },
    { title: "Crypto Midnight Market Mayhem", duration: "4:00", genre: "club vibe, lo-fi, trap", plays: 12 },
    { title: "Crypto Midnight Market Mayhem", duration: "3:36", genre: "club vibe, lo-fi, trap", plays: 3 },
    { title: "Midnight Market Mayhem", duration: "3:51", genre: "club vibe, lo-fi, trap", plays: 3 },
    { title: "Midnight Market Mayhem", duration: "2:46", genre: "club vibe, lo-fi, trap", plays: 18 },
    { title: "Spilled Vegetable Soup", duration: "2:38", genre: "club vibe, lo-fi, trap", plays: 16 },
    { title: "Symphony of Style", duration: "1:56", genre: "club vibe, lo-fi, trap", plays: 4 },
    { title: "Symphony of Style", duration: "2:18", genre: "club vibe, lo-fi, trap", plays: 3 },
    { title: "Symphony of Styles", duration: "4:00", genre: "club vibe, lo-fi, trap", plays: 16 },
    { title: "Genre Odyssey", duration: "2:30", genre: "Multi-genre fusion", plays: 2 },
    { title: "Edgeless Universe", duration: "3:33", genre: "chillhop, glitch trap", plays: 8 },
    { title: "Turnt Up Vibes", duration: "2:32", genre: "club hip hop, trap", plays: 5 },
    { title: "Sweet Heat Symphony", duration: "2:49", genre: "frostwave Chillhop", plays: 3 },
    { title: "Sweet Heat Symphony", duration: "3:08", genre: "frostwave Chillhop", plays: 4 },
    { title: "Chill Frost Flow", duration: "3:23", genre: "frostwave Chillhop", plays: 12 },
    { title: "Chill Frost Flow", duration: "2:38", genre: "frostwave Chillhop", plays: 3 },
    { title: "City Nights", duration: "3:34", genre: "frostwave Chillhop", plays: 2 },
    { title: "City Nights, No Heat, Still Sweet", duration: "4:00", genre: "Frostwave, Chillhop", plays: 8 },
    { title: "Iced Cake", duration: "3:18", genre: "frostwave Chillhop", plays: 2 },
    { title: "Iced Cake", duration: "2:26", genre: "frostwave Chillhop", plays: 2 },
    { title: "Iced Gambits", duration: "4:00", genre: "frostwave Chillhop", plays: 1 },
    { title: "Iced Gambits", duration: "4:00", genre: "frostwave Chillhop", plays: 6 },
    { title: "Frostbound Fortunes", duration: "4:00", genre: "frostwave Chillhop", plays: 7 },
    { title: "Rollin' Dice, Chasing Ice", duration: "2:15", genre: "frostwave Chillhop", plays: 2 },
    { title: "Rollin' Twice", duration: "1:55", genre: "frostwave Chillhop", plays: 1 },
    { title: "Rollin' Twice", duration: "1:47", genre: "frostwave Chillhop", plays: 1 },
    { title: "New Dawn Heat", duration: "1:46", genre: "frostwave Chillhop", plays: 2 },
    { title: "Mamacita Magic", duration: "4:00", genre: "Chillhop, Trap", plays: 7 },
    { title: "Mamacita Magic", duration: "3:31", genre: "Chillhop, Trap", plays: 2 },
    { title: "Timeless Beats", duration: "4:00", genre: "Chillhop, Trap", plays: 1 },
    { title: "Rain Nostalgia", duration: "3:54", genre: "Chillhop, Trap", plays: 2 },
    { title: "Rain Nostalgia", duration: "4:00", genre: "Chillhop, Trap", plays: 1 },
    { title: "Rain Nostalgia", duration: "4:00", genre: "Chillhop, Trap", plays: 2 },
    { title: "Wake Up Call's", duration: "4:00", genre: "chillhop, Trap", plays: 6 },
    { title: "Wake-Up Call", duration: "2:43", genre: "chillhop, Trap", plays: 6 },
    { title: "Blink of an Eye", duration: "3:57", genre: "chillhop, Trap", plays: 1 },
    { title: "Underground Voyage", duration: "2:08", genre: "chillhop, Trap", plays: 2 },
    { title: "Reigns The Glitch Bitch", duration: "2:40", genre: "Underground Rap trap", plays: 1 },
    { title: "Reigns The Glitch Bitch Queen", duration: "3:59", genre: "glitch techno", plays: 1 },
    { title: "Glitch Queen Reigns", duration: "4:00", genre: "trap rap club beats", plays: 1 },
    { title: "Turn What Up !", duration: "4:00", genre: "trap rap club beats", plays: 23 },
    { title: "Turn Down What?", duration: "4:00", genre: "trap rap club beats", plays: 2 },
    { title: "Betta Twitch Cuz I'm The Glitch", duration: "2:45", genre: "trap rap club beats", plays: 14 },
    { title: "Bitch Betta Twitch Cuz I'm The Glitch", duration: "3:25", genre: "trap rap club beats", plays: 1 },
    { title: "Bitch, I'm the Glitch", duration: "4:00", genre: "rap trap club beats", plays: 4 },
    { title: "Glitch Slowdown", duration: "4:00", genre: "rap trap club beats", plays: 4 },
    { title: "Glitch Glam Showdown", duration: "2:43", genre: "rap trap club beats", plays: 3 },
    { title: "Turn Up Showdown", duration: "3:33", genre: "Beat Fusion, Flow Funk", plays: 1 },
    { title: "Turn Up the City Night", duration: "4:00", genre: "NeoTribalTech, R&B", plays: 3 },
    { title: "Turn Up the City Lights", duration: "3:07", genre: "NeoTribalTech, R&B", plays: 2 },
    { title: "Turn Up the City Lights", duration: "3:27", genre: "NeoTribalTech, R&B", plays: 4 },
    { title: "Groove Meditation", duration: "3:14", genre: "dnb, chillhop, glitch", plays: 1 },
    { title: "City heat", duration: "2:21", genre: "dnb, chillhop, glitch", plays: 1 },
    { title: "City Lights", duration: "3:15", genre: "dnb, chillhop, glitch", plays: 5 },
    { title: "Starfall Groove", duration: "4:00", genre: "ethereal, tribal drums", plays: 1 },
    { title: "Starfall Exodus", duration: "2:38", genre: "Tribal Tech, Chillhop", plays: 10 },
    { title: "Starfall Exodus", duration: "1:49", genre: "Tribal Tech, Chillhop", plays: 1 },
    { title: "Interstellar Jam", duration: "2:27", genre: "Tribal Tech, Chillhop", plays: 1 },
    { title: "Free Conversations", duration: "2:02", genre: "dnb, chillhop, glitch", plays: 16 },
    { title: "DJ Battles", duration: "3:20", genre: "dnb, chillhop, glitch", plays: 10 },
    { title: "DJ Battles", duration: "3:03", genre: "dnb, chillhop, glitch", plays: 1 },
    { title: "DJ Battle", duration: "3:03", genre: "dnb, chillhop, glitch", plays: 8 },
    { title: "Slaptic Vibes", duration: "3:59", genre: "dnb, chillhop, glitch", plays: 2 },
    { title: "Slaptics Vibe", duration: "3:18", genre: "dnb, chillhop, glitch", plays: 1 },
    { title: "Galactic Vibes", duration: "3:01", genre: "dnb, chillhop, glitch", plays: 1 },
    { title: "Galactic Vibes", duration: "3:25", genre: "dnb, chillhop, glitch", plays: 1 },
    { title: "Space Dreamers", duration: "4:00", genre: "tribal tech, chillhop", plays: 1 },
    { title: "AI Rave", duration: "3:33", genre: "NeoTribal, Jazz, Glitch", plays: 2 },
    { title: "AI Rave", duration: "2:48", genre: "NeoTribal, Jazz, Glitch", plays: 2 },
    { title: "Why Instrumental All These Genres ?", duration: "2:52", genre: "NeoTribal, Jazz, Glitch", plays: 1 },
    { title: "Why All These Genres?", duration: "3:37", genre: "NeoTribal, Jazz, Glitch", plays: 2 },
    { title: "All these genres", duration: "1:49", genre: "NeoTribal, Jazz, Glitch", plays: 6 },
    { title: "/ \\ /_______\\ | R A| | I I| |", duration: "4:00", genre: "NeoTribal, Jazz, Glitch", plays: 8 },
    { title: "Rest To Test", duration: "3:24", genre: "NeoTribal, Jazz, Glitch", plays: 1 },
    { title: "Rest To Test", duration: "3:45", genre: "NeoTribal, Jazz, Glitch", plays: 18 },
    { title: "ArIve", duration: "2:43", genre: "NeoTribal, Jazz, Glitch", plays: 14 },
    { title: "R AI V", duration: "4:00", genre: "NeoTribal, Jazz, Glitch", plays: 8 },
    { title: "R AI V", duration: "4:00", genre: "NeoTribal, Jazz, Glitch", plays: 50 },
    { title: "R AI V", duration: "1:06", genre: "NeoTribal, Jazz, Glitch", plays: 12 },
    { title: "rAIve", duration: "2:33", genre: "NeoTribal, Jazz, Glitch", plays: 2 },
    { title: "rom rove", duration: "3:48", genre: "NeoTribal, Jazz, Glitch", plays: 1 },
    { title: "Development From Grove", duration: "2:35", genre: "NeoTribal, Jazz, Glitch", plays: 3 },
    { title: "AIMaze", duration: "1:07", genre: "NeoTribal, Jazz, Glitch", plays: 8 },
    { title: "From Grove HuH", duration: "1:37", genre: "NeoTribal, Jazz, Glitch", plays: 1 },
    { title: "From Grove", duration: "2:36", genre: "NeoTribal, Jazz, Glitch", plays: 4 },
    { title: "The Passage of Time", duration: "4:00", genre: "TribalTech, QuantumJazz", plays: 7 },
    { title: "Passage of Time", duration: "4:00", genre: "NeoTribalTech, QuantumJazz", plays: 2 },
    { title: "The Passage of Time", duration: "4:00", genre: "NeoTribalTech, QuantumJazz", plays: 4 },
    { title: "Expedition Beyond", duration: "4:00", genre: "NeoTribalTech, QuantumJazz", plays: 1 },
    { title: "Starfall Jazz", duration: "2:05", genre: "NeoTribalTech, QuantumJazz", plays: 2 },
    { title: "DJ Starfall", duration: "4:00", genre: "NeoTribalTech, QuantumJazz", plays: 6 },
    { title: "Starfall Jazz", duration: "3:59", genre: "NeoTribalTech, QuantumJazz", plays: 3 },
    { title: "Quantum Jazz", duration: "4:00", genre: "NeoTribalTech, QuantumJazz", plays: 4 },
    { title: "Quantum Jazz", duration: "2:09", genre: "NeoTribalTech, QuantumJazz", plays: 1 },
    { title: "Quantum Jazz", duration: "3:47", genre: "NeoTribalTech, QuantumJazz", plays: 2 },
    { title: "Nite Flux", duration: "4:00", genre: "NeoTribalTech, QuantumJazz", plays: 6 },
    { title: "Nity Flux Face", duration: "4:00", genre: "NeoTribalTech, QuantumJazz", plays: 2 },
    { title: "Nity Flux", duration: "4:00", genre: "NeoTribalTech, QuantumJazz", plays: 4 },
    { title: "Serenity Flux", duration: "2:47", genre: "NeoTribalTech, QuantumJazz", plays: 2 },
    { title: "Mid Mosaic", duration: "1:04", genre: "disco, trap, lo-fi, chillhop", plays: 7 },
    { title: "Midnight Mosaic", duration: "1:58", genre: "club vibe, lo-fi, trap", plays: 1 },
    { title: "What's the Vibe Gonna Be?", duration: "3:16", genre: "Wonky Trap, hip hop", plays: 4 },
    { title: "What's the Vibe Gonna Be?", duration: "2:44", genre: "Wonky Trap, hip hop", plays: 4 },
    { title: "Crypto Dreams in Neon Dreams", duration: "3:32", genre: "Wonky Trap, hip hop", plays: 2 },
    { title: "Dream in Concrete Jungles", duration: "3:40", genre: "Wonky Trap, hip hop", plays: 1 },
    { title: "Neon Dreams in Concrete Jungles", duration: "1:53", genre: "Wonky Trap, hip hop", plays: 2 },
    { title: "Neon Dreams in Concrete Jungles", duration: "3:14", genre: "Wonky Trap, hip hop", plays: 2 },
    { title: "Psychedelic Urban Odyssey", duration: "2:14", genre: "Wonky Trap, hip hop", plays: 5 },
    { title: "Neon Palette", duration: "3:55", genre: "Wonky Trap, hip hop", plays: 2 },
    { title: "Neon Palette", duration: "3:00", genre: "Wonky Trap, hip hop", plays: 1 },
    { title: "Wonky Colors", duration: "2:56", genre: "Wonky Trap, hip hop", plays: 3 },
    { title: "Twilight Trapezoid", duration: "3:16", genre: "Wonky Trap, hip hop", plays: 3 },
    { title: "Welcome to the Cyber Twilight Zone", duration: "3:24", genre: "Wonky Trap, hip hop", plays: 4 },
    { title: "Welcome to the Cyber Twilight Zone", duration: "3:19", genre: "Wonky Trap, hip hop", plays: 9 },
    { title: "Cryp Groove", duration: "2:53", genre: "Wonky Trap, hip hop", plays: 12 },
    { title: "Groove", duration: "2:39", genre: "Wonky Trap, hip hop", plays: 7 },
    { title: "Crypto Groove", duration: "2:27", genre: "Wonky Trap, hip hop", plays: 6 },
    { title: "Crypto Groove", duration: "3:52", genre: "Wonky Trap, hip hop", plays: 8 },
    { title: "Elites Pulse", duration: "3:38", genre: "Wonky Trap, hip hop", plays: 12 },
    { title: "Smooth Pulse", duration: "3:33", genre: "Wonky Trap, hip hop", plays: 10 },
    { title: "Sureal Pulse", duration: "4:00", genre: "Wonky Trap, hip hop", plays: 12 },
    { title: "Elite Pulse", duration: "3:37", genre: "Wonky Trap, hip hop", plays: 12 },
    { title: "Elite Pulse", duration: "2:51", genre: "Wonky Trap, hip hop", plays: 10 },
    { title: "Elite Pulse", duration: "4:00", genre: "Wonky Trap, hip hop", plays: 10 },
    { title: "Digital Dimes", duration: "2:41", genre: "Wonky Trap, hip hop", plays: 10 },
    { title: "Lines To Digital Dimes", duration: "2:23", genre: "Wonky Trap, hip hop", plays: 12 },
    { title: "Lines an Dimes", duration: "4:00", genre: "Wonky Trap, hip hop", plays: 2 },
    { title: "Ya", duration: "4:00", genre: "Wonky Trap, hip hop", plays: 14 },
    { title: "Cyber Lines Digital Dimes", duration: "2:29", genre: "Wonky Trap, hip hop", plays: 16 },
    { title: "Dirty Digital", duration: "2:25", genre: "Wonky Trap, hip hop", plays: 14 },
    { title: "Slo Bpm", duration: "4:00", genre: "Wonky Trap, hip hop", plays: 8 },
    { title: "Sax Cyber Line Digital Dimes", duration: "4:00", genre: "Wonky Trap, hip hop", plays: 10 },
    { title: "Cyber Lines Digital Dimes", duration: "4:00", genre: "Wonky Trap, hip hop", plays: 14 },
    { title: "Cyber Lines Digital Dimes", duration: "2:53", genre: "Wonky Trap, hip hop", plays: 3 },
    { title: "Cyber Lines Digital Dimes", duration: "3:19", genre: "Wonky Trap, hip hop", plays: 9 },
    { title: "Cyber Lines & Digital Dimes", duration: "1:37", genre: "Wonky Trap, hip hop", plays: 14 },
    { title: "Cyber Lines & Digital Dimes", duration: "2:14", genre: "Wonky Trap, hip hop", plays: 14 },
    { title: "Digital Lines & Cyber Dimes", duration: "1:32", genre: "Wonky Trap, hip hop", plays: 8 },
    { title: "Digital Lines & Cyber Dimes", duration: "3:03", genre: "Wonky Trap, hip hop", plays: 10 },
    { title: "PsyTrap Delirium", duration: "3:08", genre: "Wonky Trap, hip hop", plays: 20 },
    { title: "Stack Da City", duration: "3:11", genre: "Wonky Trap, hip hop", plays: 14 },
    { title: "Stack City", duration: "1:27", genre: "Wonky Trap, hip hop", plays: 9 },
    { title: "Stack City Beats", duration: "2:07", genre: "trap, glitch, techno", plays: 10 },
    { title: "Stack City Beats", duration: "2:24", genre: "trap, glitch, techno", plays: 18 },
    { title: "Stack City", duration: "2:30", genre: "glitch techno", plays: 12 },
    { title: "Stack City", duration: "2:17", genre: "glitch techno", plays: 12 },
    { title: "Shadows Pulse", duration: "3:16", genre: "Underground Rap & Techno", plays: 18 },
    { title: "Shadows Pulse", duration: "3:02", genre: "Underground Rap & Techno", plays: 12 },
    { title: "Shadows Pulse", duration: "2:49", genre: "Underground Rap & Techno", plays: 10 },
    { title: "Shadows Pulse", duration: "2:24", genre: "Underground Rap & Techno", plays: 9 },
    { title: "Shadows Pulse", duration: "2:36", genre: "Underground Rap & Techno", plays: 16 },
    { title: "Shadow Pulse", duration: "3:29", genre: "Underground Rap & Techno", plays: 14 },
    { title: "Shadow Pulse", duration: "2:39", genre: "Underground Rap & Techno", plays: 16 },
    { title: "Shadow Pulse", duration: "3:10", genre: "Underground Rap & Techno", plays: 12 },
    { title: "Rhythm Rides", duration: "4:00", genre: "Glitch, Dance, Trance", plays: 10 },
    { title: "Cosmic Rhythm Ride", duration: "4:00", genre: "Glitch, Dance, Trance", plays: 16 },
    { title: "Flow", duration: "4:00", genre: "Glitch, orchestral, trap", plays: 40 },
    { title: "Trap Me Inu", duration: "3:29", genre: "Glitch, orchestral, trap", plays: 3 },
    { title: "Trap Me", duration: "3:23", genre: "Glitch, orchestral, trap", plays: 5 },
    { title: "Echoes Trapped", duration: "2:47", genre: "Glitch, Dance, trap", plays: 6 },
    { title: "Light It Up", duration: "2:20", genre: "club beats, hip hop, trap", plays: 3 },
    { title: "Fire It Up", duration: "2:15", genre: "club beats, hip hop, trap", plays: 8 },
    { title: "The Night Owl", duration: "1:58", genre: "club beats, hip hop, trap", plays: 4 },
    { title: "Night Pulse's", duration: "2:58", genre: "club beats, hip hop, trap", plays: 3 },
    { title: "Club Pulse", duration: "4:00", genre: "club beats, hip hop, trap", plays: 7 },
    { title: "Astro Pulse", duration: "2:51", genre: "club beats, hip hop, trap", plays: 12 },
    { title: "Starfall Pulse", duration: "3:41", genre: "club beats, hip hop, trap", plays: 2 },
    { title: "Starfall Pulse", duration: "2:14", genre: "club beats, hip hop, trap", plays: 4 },
    { title: "Seek the Truth", duration: "3:36", genre: "psychedelic rock, glitch", plays: 40 },
    { title: "Timeless", duration: "3:07", genre: "psychedelic rock, glitch", plays: 5 },
    { title: "Timeless Byte", duration: "2:12", genre: "psychedelic rock, glitch", plays: 7 },
    { title: "A Instrumental Was Born", duration: "1:21", genre: "psychedelic rock, glitch", plays: 7 },
    { title: "A Melody Was Born", duration: "3:39", genre: "psychedelic rock, glitch", plays: 4 },
    { title: "Welcome To The Cyber Show", duration: "2:59", genre: "Electronic", plays: 5 },
    { title: "Embrace", duration: "3:59", genre: "Shoegaze", plays: 5 },
    { title: "Chaos Embrace", duration: "3:49", genre: "Shoegaze", plays: 7 },
    { title: "Username: The Untold Story", duration: "2:28", genre: "spoken word, comedy", plays: 7 },
    { title: "Username Unraveled", duration: "3:59", genre: "spoken word, comedy", plays: 5 },
    { title: "Yum Audio Soup", duration: "4:00", genre: "glitch dynamics", plays: 3 },
    { title: "Audio Soup", duration: "4:00", genre: "glitch dynamics", plays: 7 },
    { title: "Rhythmic Hearts", duration: "4:00", genre: "Urban Latin Electronica", plays: 5 },
    { title: "Dancefloor Chronicles", duration: "3:09", genre: "Urban Latin Electronica", plays: 2 },
    { title: "Heartbeat in the Bassline", duration: "4:00", genre: "Latin Electronica", plays: 3 },
    { title: "Future Echoes of Us", duration: "4:00", genre: "Latin Electronica, rap", plays: 20 },
    { title: "Rythms And Echoes of Us", duration: "2:34", genre: "Latin Electronica, rap", plays: 40 },
    { title: "Echoes of Us", duration: "4:00", genre: "Latin Electronica, rap", plays: 4 },
    { title: "Instrumental Club 0f Echoes", duration: "2:13", genre: "club, Latin, rap", plays: 5 },
    { title: "Club Queen 0f Echoes", duration: "4:00", genre: "club, Latin, rap", plays: 3 },
    { title: "Club of Echoes", duration: "3:09", genre: "club, Latin, rap", plays: 1 },
    { title: "Glitch In Love", duration: "3:31", genre: "Electronic, Glitch", plays: 4 },
    { title: "Neon Odyssey", duration: "3:35", genre: "Electronic", plays: 2 },
    { title: "Chaos Culture", duration: "4:00", genre: "Industrial Electronica", plays: 1 },
    { title: "Chaos Cutler", duration: "3:26", genre: "Industrial Electronica", plays: 10 },
    { title: "Bpm Dance", duration: "4:00", genre: "Quantum Flux Orchestral", plays: 7 },
    { title: "Guardians of the Eternal Dance", duration: "4:00", genre: "Ethereal, rhythmic", plays: 6 },
    { title: "AI Music Fusion", duration: "2:16", genre: "Multi-genre fusion", plays: 1 },
    { title: "The Ultimate Fusion Journey", duration: "4:00", genre: "Multi-genre fusion", plays: 5 },
    { title: "The Ultimate Fusion", duration: "2:39", genre: "Multi-genre fusion", plays: 10 },
    { title: "Neon Shadow", duration: "3:06", genre: "Wonky Trap Symphony", plays: 6 },
    { title: "Thoughts", duration: "1:51", genre: "Futuristic Latin Trap", plays: 2 },
    { title: "F* You, Helene", duration: "3:50", genre: "Americana/folk, glitchy", plays: 4 },
    { title: "Be the Beat", duration: "4:00", genre: "Electronic dance", plays: 5 },
    { title: "Beyond the Beats", duration: "3:15", genre: "Electronic trance", plays: 7 },
    { title: "Starfall Odyssey", duration: "3:23", genre: "Electronic, acid house", plays: 8 },
    { title: "Wake up, it's time to moon", duration: "4:00", genre: "funky pop-hop", plays: 7 },
    { title: "The Last AI Generation", duration: "2:36", genre: "Synthwave with acoustic", plays: 4 },
    { title: "Paint the Sky", duration: "2:32", genre: "Freestyle, 120 BPM", plays: 10 },
    { title: "The Smoky Mountain Elixir", duration: "3:26", genre: "Appalachian Folk", plays: 7 },
    { title: "Ballad of Popcorn Sutton", duration: "2:57", genre: "Country/Folk", plays: 3 },
    { title: "Lazy Afternoon", duration: "3:50", genre: "electronic, dance", plays: 10 },
    { title: "Sunrise Symphony", duration: "2:11", genre: "electronic, dance", plays: 5 },
    { title: "Waves of the Cosmos", duration: "2:00", genre: "electronic, dance", plays: 5 },
    { title: "Waves of the Cosmos", duration: "0:48", genre: "electronic, dance", plays: 9 },
    { title: "Orion Starfall", duration: "4:00", genre: "Electronic voiceover", plays: 16 },
    { title: "Echoes of Us", duration: "3:18", genre: "Cybernetic Symphony", plays: 6 },
    { title: "Cosmos", duration: "2:56", genre: "Cybernetic Symphony", plays: 2 },
    { title: "Dancing Shadows", duration: "4:00", genre: "Moombahton, Wonky Trap", plays: 3 },
    { title: "Sunshine on the Water", duration: "4:00", genre: "Moombahton, Wonky Trap", plays: 14 },
    { title: "Echoes of Eternity", duration: "4:00", genre: "Ambient space music", plays: 5 },
    { title: "Come dance", duration: "4:00", genre: "glitch moombahtan", plays: 7 },
    { title: "Whispered Secrets", duration: "3:36", genre: "Hip hop, trap beats", plays: 4 },
    { title: "Sounscape", duration: "3:59", genre: "Glitch, Orchestral", plays: 50 },
    { title: "Streets", duration: "4:00", genre: "Orchestral Rock", plays: 12 },
    { title: "Wasteland", duration: "3:18", genre: "Rock ballad", plays: 12 },
    { title: "Crypto Wasteland", duration: "4:00", genre: "Classic Rock, Synthwave", plays: 5 },
    { title: "Whimsical Forces of Wonderland", duration: "2:51", genre: "Glitchy ballad, Latin Trap", plays: 20 },
    { title: "The Funked Verse", duration: "3:38", genre: "Glitchy ballad, Latin Trap", plays: 16 },
    { title: "The Funked Verse", duration: "4:00", genre: "Glitchy Latin Trap", plays: 12 },
    { title: "Echoes of the Funky Universe", duration: "4:00", genre: "EchoWave Funk", plays: 5 },
    { title: "Echoes of the Funky Universe", duration: "4:00", genre: "EchoWave Funk", plays: 6 },
    { title: "The Echo Faded", duration: "2:40", genre: "Glitchy Funky beats", plays: 5 },
    { title: "Whisper of the Echo Fade", duration: "4:00", genre: "Glitch Funky beats", plays: 23 },
    { title: "Whisper of the Echoes", duration: "3:05", genre: "EchoWave Symphony", plays: 16 },
    { title: "Ancient Lore", duration: "3:15", genre: "Epic Viking Throat Symphony", plays: 40 },
    { title: "Groove Symphony", duration: "2:24", genre: "Orchestral symphonies, trap", plays: 29 },
    { title: "Galactic Funk Symphony", duration: "2:24", genre: "Neo-Symphonic Trap", plays: 20 },
    { title: "Eternal Fusion: A Journey Through Sound", duration: "0:54", genre: "Epic Orchestral EDM", plays: 4 },
    { title: "Global Beat", duration: "3:28", genre: "World Fusion Bass", plays: 18 },
    { title: "Royalty in the Streets", duration: "2:20", genre: "Neo-Symphonic Trap", plays: 12 },
    { title: "AI DJ, Come Alive", duration: "3:10", genre: "Neo-Symphonic Trap", plays: 50 },
    { title: "Typical", duration: "4:00", genre: "glitch-moombahton", plays: 16 },
    { title: "4:20 AM Shenanigans", duration: "2:45", genre: "pop-reggae", plays: 40 },
    { title: "Let's Fucking Go! Crypto", duration: "3:06", genre: "EDM, Hip Hop, Pop", plays: 5 },
    { title: "Let's Fucking Go! Crypto", duration: "3:11", genre: "EDM, Hip Hop, Pop", plays: 36 },
    { title: "Dawn of a New Day", duration: "2:56", genre: "Glitch-Moombahton", plays: 7 },
    { title: "Glitch", duration: "4:00", genre: "glitch-moombahton", plays: 77 },
    { title: "Glitch Bitch", duration: "3:05", genre: "dirty south hip hop", plays: 23 },
    { title: "Night Orchid", duration: "3:38", genre: "Pop, EDM, Hip-Hop", plays: 29 },
    { title: "Stay Epic, Tech Fam!", duration: "3:42", genre: "Trap, Pop, EDM", plays: 16 },
    { title: "Blockchain Ballin'", duration: "1:17", genre: "Versatile (Hip-Hop/Rap)", plays: 56 },
    { title: "Ten on it", duration: "1:49", genre: "edm new age rap", plays: 40 }
];